#!/usr/bin/env python3
"""
Migrate data from ZKTeco/BioTime PostgreSQL dump to Laravel HRM database.

This script reads a PostgreSQL dump file (generated by pg_dump) and imports
the data into the Laravel application's SQLite/MySQL database.

Usage:
    python migrate_to_laravel.py [--db DB_PATH] [--dump DUMP_FILE]
                                 [--step STEP] [--dry-run]

Steps:
    all        - Run all migration steps (default)
    companies  - Import companies only
    branches   - Import branches only
    departments - Import departments only
    positions  - Import positions only
    zones      - Import zones/areas only
    shifts     - Import shifts (from time intervals) only
    employees  - Import employees/users only
    devices    - Import fingerprint devices only
    attendance - Import attendance transactions only
    holidays   - Import holidays only
"""

import argparse
import hashlib
import json
import os
import re
import sqlite3
import sys
import time
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path

try:
    import pymysql

    HAS_PYMYSQL = True
except ImportError:
    HAS_PYMYSQL = False

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent

DEFAULT_DUMP = PROJECT_DIR / "20260715204044.sql"
DEFAULT_DB = PROJECT_DIR / "database" / "database.sqlite"
DEFAULT_ENV = PROJECT_DIR / ".env"

BATCH_SIZE = 500  # Number of rows per batch insert
MYSQL_BATCH = 200  # MySQL max placeholder limit

# Gender mapping
GENDER_MAP = {"M": "male", "F": "female", "m": "male", "f": "female"}

# Employment type mapping
EMP_TYPE_MAP = {1: "full_time", 2: "part_time", 3: "contract", 4: "temporary", 5: "intern"}

# Device status mapping
DEVICE_STATE_MAP = {0: "offline", 1: "online", 2: "maintenance", 3: "deactivated"}

# Punch type mapping
PUNCH_STATE_MAP = {"0": "check_in", "1": "check_out", "2": "check_in", "4": "check_out", "255": "check_in"}

# Verify type
VERIFY_TYPE_MAP = {0: "fingerprint", 1: "fingerprint", 2: "card", 3: "password", 4: "face", 15: "fingerprint"}

# Work days for shifts (default Sunday-Thursday for Arabic countries)
DEFAULT_WORK_DAYS = [0, 1, 2, 3, 4]  # Sunday=0 to Thursday=4

# ---------------------------------------------------------------------------
# PostgreSQL dump parser
# ---------------------------------------------------------------------------


class PgDumpParser:
    """Parse a PostgreSQL dump file and extract COPY data."""

    def __init__(self, filepath: Path):
        self.filepath = filepath
        self._tables_data: dict[str, list[list[str]]] = {}
        self._table_columns: dict[str, list[str]] = {}

    def parse(self, tables: list[str] | None = None) -> None:
        """Parse the dump file and extract data for the specified tables.

        Args:
            tables: List of table names to extract. If None, extract all.
        """
        print(f"Parsing {self.filepath} ({self.filepath.stat().st_size / 1024 / 1024:.1f} MB)...")

        current_table = None
        current_cols: list[str] = []
        buf: list[str] = []
        in_copy = False
        line_count = 0

        with open(self.filepath, "r", encoding="utf-8", errors="replace") as f:
            for raw_line in f:
                line = raw_line.rstrip("\n").rstrip("\r")

                if in_copy:
                    if line == "\\.":
                        # End of COPY data
                        if current_table and (tables is None or current_table in tables):
                            self._table_columns[current_table] = current_cols
                            self._tables_data[current_table] = self._parse_data_rows(buf, len(current_cols))
                            print(f"  ✓ {current_table}: {len(self._tables_data[current_table])} rows")
                        in_copy = False
                        current_table = None
                        current_cols = []
                        buf = []
                    else:
                        buf.append(line)
                    continue

                m = re.match(r"COPY public\.(\w+)\s*\((.*?)\)\s+FROM stdin;", line)
                if m:
                    table_name = m.group(1)
                    cols_str = m.group(2)
                    current_cols = [c.strip() for c in cols_str.split(",")]
                    in_copy = True
                    current_table = table_name
                    buf = []
                    continue

                line_count += 1
                if line_count % 100000 == 0:
                    pass  # silent progress

        print(f"Parsing complete. {len(self._tables_data)} tables extracted.")
        print()

    def _parse_data_rows(self, lines: list[str], col_count: int) -> list[list[str]]:
        """Parse tab-separated data lines into rows of column values."""
        rows: list[list[str]] = []
        for line in lines:
            if not line.strip():
                continue
            # Split by tab, handling \N as NULL
            values = line.split("\t")
            # Pad or truncate to match column count
            if len(values) < col_count:
                values.extend(["\\N"] * (col_count - len(values)))
            elif len(values) > col_count:
                values = values[:col_count]
            rows.append(values)
        return rows

    def get_table_data(self, table: str) -> list[dict[str, str | None]]:
        """Get table data as list of dicts with column name keys."""
        if table not in self._tables_data:
            return []

        cols = self._table_columns.get(table, [])
        rows = self._tables_data[table]
        result: list[dict[str, str | None]] = []

        for row in rows:
            data: dict[str, str | None] = {}
            for i, col in enumerate(cols):
                if i < len(row):
                    val = row[i]
                    data[col] = None if val == "\\N" else val
                else:
                    data[col] = None
            result.append(data)

        return result

    @property
    def available_tables(self) -> list[str]:
        return sorted(self._tables_data.keys())


# ---------------------------------------------------------------------------
# Database helpers
# ---------------------------------------------------------------------------


class Database:
    """Simple DB abstraction supporting SQLite and MySQL."""

    def __init__(self, conn, db_type: str):
        self.conn = conn
        self.db_type = db_type

    def execute(self, sql: str, params: tuple = ()):
        """Execute SQL with proper placeholder handling."""
        if self.db_type == "mysql":
            sql = sql.replace("?", "%s")
            sql = sql.replace("INSERT OR IGNORE", "INSERT IGNORE")
            sql = sql.replace("INSERT OR REPLACE", "REPLACE")
        cur = self.conn.cursor()
        cur.execute(sql, params)
        # For auto-increment: if table has an explicit ID column and id is provided,
        # we shouldn't update auto-increment sequence
        return cur

    def executemany(self, sql: str, params_list: list[tuple]):
        """Execute SQL with multiple parameter sets."""
        if self.db_type == "mysql":
            sql = sql.replace("?", "%s")
            sql = sql.replace("INSERT OR IGNORE", "INSERT IGNORE")
            sql = sql.replace("INSERT OR REPLACE", "REPLACE")
        cur = self.conn.cursor()
        cur.executemany(sql, params_list)
        return cur

    def commit(self):
        """Commit pending changes."""
        self.conn.commit()

    def close(self):
        """Close the connection."""
        try:
            if self.db_type == "mysql":
                self.conn.close()
            else:
                self.conn.close()
        except Exception:
            pass

    def enable_foreign_keys(self):
        """Enable foreign key checks."""
        if self.db_type == "mysql":
            self.execute("SET FOREIGN_KEY_CHECKS=1")
        else:
            self.execute("PRAGMA foreign_keys=ON")


def open_db(db_path: Path, use_mysql: bool = False) -> Database:
    """Open database connection (SQLite or MySQL)."""
    if use_mysql:
        env_file = db_path  # db_path is actually the .env file path in mysql mode
        credentials = _read_env(env_file)
        conn = pymysql.connect(
            host=credentials["host"],
            port=credentials["port"],
            user=credentials["user"],
            password=credentials["password"],
            database=credentials["database"],
            charset="utf8mb4",
            autocommit=False,
        )
        db = Database(conn, "mysql")
        db.execute("SET FOREIGN_KEY_CHECKS=0")
        db.execute("SET NAMES utf8mb4")
        db.execute("SET CHARACTER SET utf8mb4")
        return db

    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=OFF")
    conn.execute("PRAGMA foreign_keys=OFF")
    return Database(conn, "sqlite")


def _read_env(env_path: Path) -> dict:
    """Read Laravel .env file and extract DB credentials."""
    creds = {
        "host": "127.0.0.1",
        "port": 3306,
        "user": "root",
        "password": "",
        "database": "laravel",
    }
    if not env_path.exists():
        print(f"WARNING: .env file not found at {env_path}, using defaults")
        return creds

    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key == "DB_HOST":
                    creds["host"] = value
                elif key == "DB_PORT":
                    creds["port"] = int(value) if value else 3306
                elif key == "DB_USERNAME":
                    creds["user"] = value
                elif key == "DB_PASSWORD":
                    creds["password"] = value
                elif key == "DB_DATABASE":
                    creds["database"] = value
    return creds


def escape_str(val: str | None) -> str | None:
    """Escape string for SQL insertion."""
    if val is None:
        return None
    return val.replace("'", "''")


def safe_int(val: str | None, default: int | None = None) -> int | None:
    """Convert value to int safely."""
    if val is None or val.strip() == "":
        return default
    try:
        return int(val)
    except (ValueError, TypeError):
        return default


def safe_bool(val: str | None, default: bool = False) -> int:
    """Convert value to SQLite boolean (0/1)."""
    if val is None:
        return 1 if default else 0
    if isinstance(val, bool):
        return 1 if val else 0
    return 1 if val.lower() in ("t", "true", "1", "yes", "on") else 0


def safe_float(val: str | None, default: float | None = None) -> float | None:
    """Convert value to float safely."""
    if val is None or val.strip() == "":
        return default
    try:
        return float(val)
    except (ValueError, TypeError):
        return default


def now_ts() -> str:
    """Return current UTC timestamp string."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def _normalize_ts(val: str | None) -> str | None:
    """Normalize a PostgreSQL timestamp to MySQL-compatible format."""
    if not val:
        return None
    # Remove timezone suffix: +08, +00:00
    val = re.sub(r"\+[0-9]{1,2}(:[0-9]{2})?$", "", val)
    # Truncate microseconds beyond 3 digits (MySQL max precision)
    val = re.sub(r"\.(\d{3})\d*", r".\1", val)
    # Replace T separator with space
    val = val.replace("T", " ")
    return val


def nullif(val: str | None) -> str:
    """Return 'NULL' if val is None, otherwise quote it."""
    if val is None:
        return "NULL"
    return f"'{escape_str(val)}'"


def nullif_int(val: int | None) -> str:
    """Return 'NULL' if val is None, otherwise the int."""
    if val is None:
        return "NULL"
    return str(val)


def nullif_float(val: float | None) -> str:
    """Return 'NULL' if val is None, otherwise the float."""
    if val is None:
        return "NULL"
    return str(val)


# ---------------------------------------------------------------------------
# Migration steps
# ---------------------------------------------------------------------------


class Migrator:
    """Main migration class that orchestrates the data import."""

    def __init__(self, parser: PgDumpParser, db: Database | None, dry_run: bool = False):
        self.parser = parser
        self.db = db
        self.is_mysql = db is not None and db.db_type == "mysql"
        self.dry_run = dry_run
        self.id_maps: dict[str, dict[int, int]] = {}  # old_id -> new_id maps
        self.stats: dict[str, int] = {}

    def exec(self, sql: str, params: tuple = ()) -> None:
        """Execute SQL if not dry run."""
        if self.dry_run:
            return
        try:
            self.db.execute(sql, params)
        except Exception as e:
            print(f"  SQL ERROR: {e}")
            print(f"  SQL: {sql[:200]}...")
            raise

    def commit(self) -> None:
        """Commit pending changes."""
        if not self.dry_run:
            self.db.commit()

    def insert_batch(self, table: str, columns: list[str], rows: list[list[str | None]]) -> int:
        """Insert multiple rows into the database."""
        if not rows:
            return 0

        cols = ", ".join(columns)
        # generate placeholders compatible with the DB driver
        placeholders = ", ".join(["?" for _ in columns])
        sql = f"INSERT INTO {table} ({cols}) VALUES ({placeholders})"

        count = 0
        for row in rows:
            if self.dry_run:
                count += 1
            else:
                try:
                    db_row = tuple(row)
                    self.db.execute(sql, db_row)
                    count += 1
                except Exception as e:
                    # Only print first few errors
                    pass
        return count

    # ==================================================================
    # Step 1: Companies
    # ==================================================================

    def migrate_companies(self) -> dict[int, int]:
        """Import companies from personnel_company to companies table."""
        print("=" * 60)
        print("Step 1: Migrating Companies")
        print("=" * 60)

        data = self.parser.get_table_data("personnel_company")
        print(f"  Found {len(data)} companies in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            company_code = row.get("company_code") or f"CMP{old_id:04d}"
            company_name = row.get("company_name") or f"Company {old_id}"
            is_default = safe_bool(row.get("is_default"))
            address = row.get("address")
            address2 = row.get("address2")
            email = row.get("email")
            phone = row.get("phone")
            city = row.get("city")
            country = row.get("country")
            state = row.get("state")
            postal_code = row.get("postal_code")
            website = row.get("website")
            logo = row.get("logo")
            old_status = safe_int(row.get("status"), 1)
            status = 1 if old_status == 1 else 0

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO companies (id, company_code, company_name, is_default,
                           address, address2, email, phone, city, country, state,
                           postal_code, website, logo, status, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, company_code, company_name, is_default,
                         address, address2, email, phone, city, country, state,
                         postal_code, website, logo, status, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting company {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["companies"] = id_map
        self.commit()
        print(f"  Migrated {count} companies")
        print()
        return id_map

    # ==================================================================
    # Step 2: Branches (create default branch per company)
    # ==================================================================

    def migrate_branches(self) -> dict[int, int]:
        """Create default branches for each company."""
        print("=" * 60)
        print("Step 2: Creating Default Branches")
        print("=" * 60)

        company_ids = self._get_ids("companies")
        id_map: dict[int, int] = {}
        branch_to_company: dict[int, int] = {}
        ts = now_ts()
        count = 0

        for company_id in company_ids:
            # Each company gets one default branch
            # Use company_id as branch_id for simplicity
            branch_code = f"BR{company_id:04d}"
            branch_name = f"Main Branch {company_id}"

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO branches (id, company_id, branch_code, branch_name,
                           is_main, status, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                        (company_id, company_id, branch_code, branch_name,
                         1, 1, ts, ts),
                    )
                    id_map[company_id] = company_id
                    branch_to_company[company_id] = company_id
                except Exception as e:
                    print(f"  ERROR creating branch for company {company_id}: {e}")
            else:
                id_map[company_id] = company_id
                branch_to_company[company_id] = company_id
            count += 1

        self.id_maps["branches"] = id_map
        self.id_maps["branch_to_company"] = branch_to_company
        self.commit()
        print(f"  Created {count} branches")
        print()
        return id_map

    # ==================================================================
    # Step 3: Departments
    # ==================================================================

    def migrate_departments(self) -> dict[int, int]:
        """Import departments from personnel_department to departments table."""
        print("=" * 60)
        print("Step 3: Migrating Departments")
        print("=" * 60)

        data = self.parser.get_table_data("personnel_department")
        print(f"  Found {len(data)} departments in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0
        skipped = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            dept_code = row.get("dept_code") or f"DEPT{old_id:04d}"
            dept_name = row.get("dept_name") or f"Department {old_id}"
            old_parent_id = safe_int(row.get("parent_dept_id"))
            old_manager_id = safe_int(row.get("dept_manager_id"))
            old_company_id = safe_int(row.get("company_id"))
            is_default = safe_bool(row.get("is_default"))

            if old_company_id is None:
                skipped += 1
                continue

            # Map branch_id = company_id (each company has 1 main branch)
            branch_id = old_company_id

            # Parent department - will be resolved by new ID
            new_parent_id = None
            if old_parent_id and old_parent_id != old_id:
                new_parent_id = old_parent_id  # We preserve original IDs

            # Manager = user reference (will be resolved after user migration)
            manager_id = old_manager_id

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO departments (id, company_id, branch_id, parent_id,
                           manager_id, department_code, department_name, status,
                           created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, old_company_id, branch_id, new_parent_id,
                         manager_id, dept_code, dept_name, 1, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting department {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["departments"] = id_map
        self.commit()
        print(f"  Migrated {count} departments (skipped {skipped})")
        print()
        return id_map

    # ==================================================================
    # Step 4: Positions
    # ==================================================================

    def migrate_positions(self) -> dict[int, int]:
        """Import positions from personnel_position to positions table."""
        print("=" * 60)
        print("Step 4: Migrating Positions")
        print("=" * 60)

        data = self.parser.get_table_data("personnel_position")
        print(f"  Found {len(data)} positions in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0
        skipped = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            position_code = row.get("position_code") or f"POS{old_id:04d}"
            position_name = row.get("position_name") or f"Position {old_id}"
            old_company_id = safe_int(row.get("company_id"))

            if old_company_id is None:
                skipped += 1
                continue

            branch_id = old_company_id  # Map to main branch

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO positions (id, company_id, branch_id, position_code,
                           position_name, status, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, old_company_id, branch_id, position_code,
                         position_name, 1, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting position {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["positions"] = id_map
        self.commit()
        print(f"  Migrated {count} positions (skipped {skipped})")
        print()
        return id_map

    # ==================================================================
    # Step 5: Zones (from areas)
    # ==================================================================

    def migrate_zones(self) -> dict[int, int]:
        """Import zones from personnel_area to zones table."""
        print("=" * 60)
        print("Step 5: Migrating Zones (from Areas)")
        print("=" * 60)

        data = self.parser.get_table_data("personnel_area")
        print(f"  Found {len(data)} areas in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0
        skipped = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            area_code = row.get("area_code") or f"ZONE{old_id:04d}"
            area_name = row.get("area_name") or f"Zone {old_id}"
            old_company_id = safe_int(row.get("company_id"))
            device_count = safe_int(row.get("device_count"), 0)
            employee_count = safe_int(row.get("employee_count"), 0)

            if old_company_id is None:
                skipped += 1
                continue

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO zones (id, company_id, code, name_ar, name_en,
                           zone_type, is_active, devices_count, employees_count,
                           created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, old_company_id, area_code, area_name, area_name,
                         "geographic", 1, device_count, employee_count, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting zone {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["zones"] = id_map
        self.commit()
        print(f"  Migrated {count} zones (skipped {skipped})")
        print()
        return id_map

    # ==================================================================
    # Step 6: Shifts (from time intervals)
    # ==================================================================

    def migrate_shifts(self) -> dict[int, int]:
        """Import shifts from att_timeinterval to shifts table."""
        print("=" * 60)
        print("Step 6: Migrating Shifts (from Time Intervals)")
        print("=" * 60)

        data = self.parser.get_table_data("att_timeinterval")
        print(f"  Found {len(data)} time intervals in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            alias = row.get("alias") or f"Shift {old_id}"
            in_time = row.get("in_time")  # e.g., "08:00:00"
            duration = safe_int(row.get("duration"), 480)  # in minutes
            allow_late = safe_int(row.get("allow_late"), 0)
            work_day = safe_float(row.get("work_day"), 1.0)
            company_id = safe_int(row.get("company_id"))

            # Calculate end_time from in_time + duration
            end_time = None
            if in_time:
                try:
                    parts = in_time.split(":")
                    h = int(parts[0])
                    m = int(parts[1]) if len(parts) > 1 else 0
                    total_min = h * 60 + m + (duration or 480)
                    end_h = (total_min // 60) % 24
                    end_m = total_min % 60
                    end_time = f"{end_h:02d}:{end_m:02d}:00"
                except (ValueError, IndexError):
                    end_time = "17:00:00"

            shift_code = f"SHIFT{old_id:04d}"
            shift_name = alias
            grace_minutes = allow_late if allow_late else 15
            break_minutes = 60  # Default
            working_hours = round((duration or 480) / 60.0, 2)

            # Work days as JSON array
            work_days = str(DEFAULT_WORK_DAYS).replace(" ", "")

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO shifts (id, company_id, branch_id, shift_code, shift_name,
                           start_time, end_time, break_minutes, grace_minutes,
                           working_hours, work_days, status, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, company_id, company_id,  # branch_id = company_id
                         shift_code, shift_name, in_time, end_time,
                         break_minutes, grace_minutes, working_hours,
                         work_days, 1, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting shift {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["shifts"] = id_map
        self.commit()
        print(f"  Migrated {count} shifts")
        print()
        return id_map

    # ==================================================================
    # Step 7: Employees / Users
    # ==================================================================

    def migrate_employees(self) -> dict[int, int]:
        """Import employees from personnel_employee to users table."""
        print("=" * 60)
        print("Step 7: Migrating Employees")
        print("=" * 60)

        data = self.parser.get_table_data("personnel_employee")
        print(f"  Found {len(data)} employees in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0
        skipped = 0
        error_count = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            emp_code = row.get("emp_code") or f"EMP{old_id:06d}"
            first_name = row.get("first_name") or ""
            last_name = row.get("last_name") or ""
            nickname = row.get("nickname") or ""
            name = f"{first_name} {last_name}".strip()

            # Generate name if empty
            if not name:
                name = nickname or emp_code

            email = row.get("email")
            # Generate email if missing
            if not email or email.strip() == "":
                email = f"emp{old_id}@hrm.local"

            # Make sure email doesn't conflict with admin
            if email == "admin@hrm.local":
                email = f"emp{old_id}@hrm.local"

            mobile = row.get("mobile") or row.get("contact_tel") or ""
            phone = mobile
            address = row.get("address")
            city = row.get("city")
            nationality = row.get("national")
            gender_raw = row.get("gender")
            gender = GENDER_MAP.get(gender_raw, "male") if gender_raw else "male"
            birthday = row.get("birthday")
            hire_date = row.get("hire_date")
            ssn = row.get("ssn") or ""
            is_active = safe_bool(row.get("is_active"), True)
            status = 1 if is_active else 0
            old_department_id = safe_int(row.get("department_id"))
            old_position_id = safe_int(row.get("position_id"))
            old_company_id = safe_int(row.get("company_id"))
            old_superior_id = safe_int(row.get("superior_id"))
            last_login = row.get("last_login")

            if old_company_id is None:
                skipped += 1
                continue

            # Branch = company (main branch)
            branch_id = old_company_id

            # Generate a hashed password from emp_code
            password_hash = hashlib.sha256(f"emp{old_id}{emp_code}".encode()).hexdigest()
            # Laravel bcrypt alternative for SQLite - store a hash prefix
            # In practice, users will use password reset
            password = f"$2y$12${password_hash[:50]}"

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO users (id, employee_code, name, first_name, last_name,
                           email, password, national_id, phone, phone2, date_of_birth,
                           gender, hire_date, status, is_active_employee,
                           company_id, branch_id, department_id, position_id,
                           manager_id, address, city, nationality,
                           last_login_at, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, emp_code, name, first_name, last_name,
                         email, password, ssn, mobile, phone, birthday,
                         gender, hire_date, status, is_active,
                         old_company_id, branch_id, old_department_id, old_position_id,
                         old_superior_id, address, city, nationality,
                         last_login, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    error_count += 1
                    if error_count <= 5:
                        print(f"  ERROR inserting employee {old_id} ({name}): {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1
            if count % 500 == 0:
                if not self.dry_run:
                    self.commit()
                print(f"  Progress: {count}/{len(data)} employees...")

        self.id_maps["employees"] = id_map
        self.commit()
        print(f"  Migrated {count} employees (skipped {skipped}, errors {error_count})")
        print()
        return id_map

    # ==================================================================
    # Step 8: Fingerprint Devices
    # ==================================================================

    def migrate_devices(self) -> dict[int, int]:
        """Import devices from iclock_terminal to fingerprint_devices table."""
        print("=" * 60)
        print("Step 8: Migrating Fingerprint Devices")
        print("=" * 60)

        data = self.parser.get_table_data("iclock_terminal")
        print(f"  Found {len(data)} devices in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            sn = row.get("sn") or f"DEV{old_id:04d}"
            alias = row.get("alias") or f"Device {old_id}"
            ip_addr = row.get("ip_address") or "0.0.0.0"
            state = safe_int(row.get("state"), 0)
            area_id = safe_int(row.get("area_id"))
            last_activity = _normalize_ts(row.get("last_activity"))
            upload_time = _normalize_ts(row.get("upload_time"))
            user_count = safe_int(row.get("user_count"), 0)
            transaction_count = safe_int(row.get("transaction_count"), 0)
            fp_count = safe_int(row.get("fp_count"), 0)
            face_count = safe_int(row.get("face_count"), 0)

            status = DEVICE_STATE_MAP.get(state, "offline")

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO fingerprint_devices (id, device_type_id, name, serial_number, ip_address,
                           port, status, last_seen_at, last_synced_at,
                           user_count, fingerprint_count, attendance_log_count,
                           created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, 1, alias, sn, ip_addr,
                         4370, status, last_activity, upload_time,
                         user_count, fp_count, transaction_count,
                         ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting device {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["devices"] = id_map
        self.commit()
        print(f"  Migrated {count} devices")
        print()
        return id_map

    # ==================================================================
    # Step 9: Attendance (raw logs + sessions)
    # ==================================================================

    def migrate_attendance(self) -> dict[int, int]:
        """Import attendance from iclock_transaction into raw_attendance_logs.
        Sessions will be created by the existing Laravel ProcessRawLogsCommand."""
        print("=" * 60)
        print("Step 9: Migrating Attendance Transactions")
        print("=" * 60)

        data = self.parser.get_table_data("iclock_transaction")
        print(f"  Found {len(data)} attendance transactions in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        log_count = 0
        skip_count = 0

        raw_logs_batch: list[tuple] = []

        for row in data:
            old_id = safe_int(row.get("id"))
            emp_code = row.get("emp_code") or ""
            emp_id = safe_int(row.get("emp_id"))
            # Normalize punch_time for MySQL compatibility
            punch_time = _normalize_ts(row.get("punch_time"))
            punch_state = row.get("punch_state") or "0"
            verify_type = safe_int(row.get("verify_type"), 0)
            work_code = row.get("work_code")
            terminal_sn = row.get("terminal_sn") or ""
            terminal_alias = row.get("terminal_alias") or ""
            terminal_id = safe_int(row.get("terminal_id"))
            source = safe_int(row.get("source"))

            if not emp_id:
                skip_count += 1
                continue

            # Map punch state to type
            punch_type = PUNCH_STATE_MAP.get(punch_state, "check_in")
            verify_type_str = VERIFY_TYPE_MAP.get(verify_type, "fingerprint")

            # Build raw_data JSON with all available context
            raw_data = {
                "emp_code": emp_code,
                "punch_state": punch_state,
                "verify_type": verify_type,
                "work_code": work_code or "",
                "terminal_sn": terminal_sn,
                "terminal_alias": terminal_alias,
                "source": source,
            }
            raw_data_json = json.dumps(raw_data, ensure_ascii=False)

            # Determine source string
            source_str = "device"
            if source == 1:
                source_str = "manual"
            elif source == 2:
                source_str = "api"
            elif source == 3:
                source_str = "adms"

            raw_logs_batch.append((
                old_id, emp_id, terminal_id, emp_code, punch_time,
                punch_type, verify_type_str, work_code,
                source_str,
                False,  # processed = false (Laravel command will process)
                None,   # processed_at = null
                ts, ts,
                None,   # ip_address
                raw_data_json,
            ))

            if len(raw_logs_batch) >= BATCH_SIZE:
                self._flush_raw_logs(raw_logs_batch)
                raw_logs_batch = []
                self.commit()

            id_map[old_id] = old_id
            log_count += 1

            if log_count % 5000 == 0:
                print(f"  Progress: {log_count}/{len(data)} transactions...")

        # Flush remaining
        if raw_logs_batch:
            self._flush_raw_logs(raw_logs_batch)

        self.id_maps["attendance_logs"] = id_map
        self.commit()
        print(f"  Migrated {log_count} raw logs (skipped {skip_count})")
        print()
        print("  NOTE: Attendance sessions are NOT created during migration.")
        print("  Run the following command to process raw logs into sessions:")
        print("    php artisan attendance:process-raw-logs")
        print()
        return id_map

    def _flush_raw_logs(self, batch: list[tuple]) -> None:
        """Insert raw attendance logs."""
        if self.dry_run or not batch:
            return
        try:
            self.db.executemany(
                """INSERT OR IGNORE INTO raw_attendance_logs
                   (id, user_id, device_id, device_user_id, punch_time,
                    punch_type, verify_type, work_code, source,
                    processed, processed_at, created_at, updated_at,
                    ip_address, raw_data)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                batch,
            )
        except Exception as e:
            print(f"  ERROR flushing raw logs: {e}")

    def _flush_sessions(self, batch: list[tuple]) -> None:
        """Insert attendance sessions."""
        if self.dry_run or not batch:
            return
        try:
            self.db.executemany(
                """INSERT OR IGNORE INTO attendance_sessions
                   (id, user_id, shift_id, device_id, raw_log_id, zone_id,
                    attendance_date, check_in_at, check_out_at,
                    expected_check_in, expected_check_out,
                    status, session_type, source,
                    work_minutes, break_minutes, late_minutes, early_leave_minutes, overtime_minutes,
                    ip_address, metadata, notes, created_by,
                    created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                batch,
            )
        except Exception as e:
            print(f"  ERROR flushing sessions: {e}")

    # ==================================================================
    # Step 10: Holidays
    # ==================================================================

    def migrate_holidays(self) -> dict[int, int]:
        """Import holidays from att_holiday to holidays table."""
        print("=" * 60)
        print("Step 10: Migrating Holidays")
        print("=" * 60)

        data = self.parser.get_table_data("att_holiday")
        print(f"  Found {len(data)} holidays in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0
        skipped = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            alias = row.get("alias") or f"Holiday {old_id}"
            start_date = row.get("start_date")
            duration_day = safe_int(row.get("duration_day"), 1)
            end_date = row.get("end_date")

            if not start_date:
                skipped += 1
                continue

            # Check if recurring (same month/day every year)
            is_recurring = False
            recurring_month = None
            recurring_day = None

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT INTO holidays (id, name_ar, name_en, code,
                           is_recurring, date, recurring_month, recurring_day,
                           category, is_paid, is_active, duration_days,
                           applies_to_all, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, alias, alias, f"HOL{old_id:04d}",
                         is_recurring, start_date, recurring_month, recurring_day,
                         "public", True, 1, duration_day,
                         True, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    print(f"  ERROR inserting holiday {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["holidays"] = id_map
        self.commit()
        print(f"  Migrated {count} holidays (skipped {skipped})")
        print()
        return id_map

    # ==================================================================
    # Step 11: Vacations / Leaves (basic)
    # ==================================================================

    def migrate_vacations(self) -> dict[int, int]:
        """Import vacations/leaves from att_leave + att_paycode."""
        print("=" * 60)
        print("Step 11: Migrating Vacations")
        print("=" * 60)

        leave_data = self.parser.get_table_data("att_leave")
        print(f"  Found {len(leave_data)} leave records in dump")

        # First, create default vacation types from paycodes
        paycode_data = self.parser.get_table_data("att_paycode")
        vac_type_map: dict[int, int] = {}
        ts = now_ts()

        for row in paycode_data:
            old_id = safe_int(row.get("id"))
            code = row.get("code") or f"VC{old_id:04d}"
            name = row.get("name") or f"Vacation Type {old_id}"
            is_paid = safe_bool(row.get("is_paid"), True)

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT OR IGNORE INTO vacation_types (id, code, name_ar, name_en,
                           is_paid, is_active, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, code, name, name, is_paid, 1, ts, ts),
                    )
                except Exception:
                    pass

            vac_type_map[old_id] = old_id

        self.commit()
        print(f"  Created {len(vac_type_map)} vacation types")

        # Now import leave records
        id_map: dict[int, int] = {}
        count = 0

        for row in leave_data:
            wf_ptr_id = safe_int(row.get("workflowinstance_ptr_id"))
            start_time = row.get("start_time")
            end_time = row.get("end_time")
            pay_code_id = safe_int(row.get("pay_code_id"))
            leave_day = safe_int(row.get("leave_day"), 0)

            if not start_time:
                continue

            # Extract employee ID from workflow instance (simplified)
            old_id = wf_ptr_id

            if not self.dry_run and old_id:
                try:
                    start_dt = start_time[:10] if start_time else None
                    end_dt = end_time[:10] if end_time else None
                    days_count = leave_day if leave_day else 1

                    self.db.execute(
                        """INSERT OR IGNORE INTO user_vacation_requests
                           (id, user_id, vacation_type_id, start_date, end_date,
                            days_count, status, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, None, pay_code_id, start_dt, end_dt,
                         days_count, "approved", ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception:
                    continue

            count += 1

        self.commit()
        print(f"  Migrated {count} vacation requests")
        print()
        return id_map

    # ==================================================================
    # Step 12: Fingerprint Templates (biodata)
    # ==================================================================

    def migrate_fingerprints(self) -> dict[int, int]:
        """Import fingerprint templates from iclock_biodata."""
        print("=" * 60)
        print("Step 12: Migrating Fingerprint Templates")
        print("=" * 60)

        data = self.parser.get_table_data("iclock_biodata")
        print(f"  Found {len(data)} fingerprint records in dump")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0
        skipped = 0

        for row in data:
            old_id = safe_int(row.get("id"))
            employee_id = safe_int(row.get("employee_id"))
            bio_no = safe_int(row.get("bio_no"), 0)
            bio_index = safe_int(row.get("bio_index"), 0)
            bio_type = safe_int(row.get("bio_type"), 0)
            bio_format = safe_int(row.get("bio_format"))
            bio_tmp = row.get("bio_tmp")  # base64 encoded template data
            major_ver = row.get("major_ver")
            minor_ver = row.get("minor_ver")
            valid = safe_bool(row.get("valid"), True)

            if not employee_id:
                skipped += 1
                continue

            # Determine template format based on bio_type
            template_format = "zk"
            finger_id = bio_index
            template_version = f"{major_ver}.{minor_ver}" if major_ver else "1.0"

            if not self.dry_run:
                try:
                    self.db.execute(
                        """INSERT OR IGNORE INTO user_fingerprints
                           (id, user_id, finger_id, template_data,
                            template_format, template_version,
                            is_master, created_at, updated_at)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (old_id, employee_id, finger_id, bio_tmp,
                         template_format, template_version,
                         0, ts, ts),
                    )
                    id_map[old_id] = old_id
                except Exception as e:
                    if count < 3:
                        print(f"  ERROR inserting fingerprint {old_id}: {e}")
                    continue
            else:
                id_map[old_id] = old_id

            count += 1

        self.id_maps["fingerprints"] = id_map
        self.commit()
        print(f"  Migrated {count} fingerprint templates (skipped {skipped})")
        print()
        return id_map

    # ==================================================================
    # Step 13: Daily Attendance Summaries (from payload data)
    # ==================================================================

    def migrate_daily_summaries(self) -> dict[int, int]:
        """Import daily attendance summaries from att_payloadattcode + att_payloadpaycode."""
        print("=" * 60)
        print("Step 13: Migrating Daily Attendance Summaries")
        print("=" * 60)

        # Use att_payloadattcode for detailed attendance code data
        attcode_data = self.parser.get_table_data("att_payloadattcode")
        print(f"  Found {len(attcode_data)} attendance code records")

        id_map: dict[int, int] = {}
        ts = now_ts()
        count = 0

        # Group by (emp_id, att_date) to build summaries
        grouped: dict[tuple[int, str], dict] = defaultdict(lambda: {
            "att_date": "",
            "emp_id": 0,
            "shift_id": None,
            "total_minutes": 0,
            "overtime_minutes": 0,
            "codes": [],
            "status": "present",
        })

        for row in attcode_data:
            emp_id = safe_int(row.get("emp_id"))
            att_date = row.get("att_date")
            duration = safe_int(row.get("duration"), 0)  # in minutes
            shift_id = safe_int(row.get("shift_id"))
            att_code_alias = row.get("att_code_alias") or ""
            hours = safe_float(row.get("hours"), 0)
            minutes_val = safe_float(row.get("minutes"), 0)

            if not emp_id or not att_date:
                continue

            key = (emp_id, att_date)
            entry = grouped[key]
            entry["emp_id"] = emp_id
            entry["att_date"] = att_date
            if shift_id:
                entry["shift_id"] = shift_id

            # Track time
            entry["total_minutes"] += duration

            # Check for overtime codes (OT, overtime, over)
            code_lower = att_code_alias.lower()
            if any(kw in code_lower for kw in ["over", "ot", "extra"]):
                entry["overtime_minutes"] += duration

            entry["codes"].append(att_code_alias)

            # Check for absent/late/leave codes
            if any(kw in code_lower for kw in ["absence", "absent"]):
                entry["status"] = "absent"
            elif any(kw in code_lower for kw in ["leave", "vacation"]):
                entry["status"] = "vacation"

        print(f"  Grouped into {len(grouped)} daily summaries")

        # Also process att_payloadpaycode for pay code data
        paycode_data = self.parser.get_table_data("att_payloadpaycode")
        if paycode_data:
            print(f"  Found {len(paycode_data)} pay code records, merging...")
            for row in paycode_data:
                emp_id = safe_int(row.get("emp_id"))
                att_date = row.get("att_date")
                duration = safe_int(row.get("duration"), 0)
                pay_code_alias = row.get("pay_code_alias") or ""
                shift_id = safe_int(row.get("shift_id"))

                if not emp_id or not att_date:
                    continue

                key = (emp_id, att_date)
                entry = grouped[key]
                entry["emp_id"] = emp_id
                entry["att_date"] = att_date
                entry["total_minutes"] += duration
                if shift_id:
                    entry["shift_id"] = shift_id

                code_lower = pay_code_alias.lower()
                if any(kw in code_lower for kw in ["over", "ot", "extra"]):
                    entry["overtime_minutes"] += duration
                if any(kw in code_lower for kw in ["absence", "absent"]):
                    entry["status"] = "absent"
                elif any(kw in code_lower for kw in ["leave", "vacation"]):
                    entry["status"] = "vacation"

                entry["codes"].append(pay_code_alias)

        # Insert summaries
        batch: list[tuple] = []
        for (emp_id, att_date), entry_data in grouped.items():
            shift_id = entry_data.get("shift_id")
            status = entry_data.get("status", "present")
            total_minutes = entry_data.get("total_minutes", 0)
            overtime_minutes = entry_data.get("overtime_minutes", 0)

            # Generate a stable ID from emp_id and date
            idx = count + 1

            if not self.dry_run:
                batch.append((
                    idx, emp_id, shift_id, att_date,
                    status, "normal",  # session_type
                    None, None,  # first_check_in, last_check_out
                    None, None,  # expected_check_in, expected_check_out
                    1,  # sessions_count
                    0, 0,  # is_first_punch, is_complete
                    total_minutes, 0, overtime_minutes, 0, 0,  # work, break, ot, late, early
                    None, ts,
                    ts, ts,
                ))

            if len(batch) >= BATCH_SIZE:
                self._flush_summaries(batch)
                batch = []

            id_map[idx] = idx
            count += 1

        if batch:
            self._flush_summaries(batch)

        self.id_maps["daily_summaries"] = id_map
        self.commit()
        print(f"  Imported {count} daily attendance summaries")
        print()
        return id_map

    def _flush_summaries(self, batch: list[tuple]) -> None:
        """Insert daily attendance summaries."""
        if self.dry_run or not batch:
            return
        try:
            self.db.executemany(
                """INSERT OR REPLACE INTO daily_attendance_summaries
                   (id, user_id, shift_id, summary_date,
                    status, session_type,
                    first_check_in_at, last_check_out_at,
                    expected_check_in, expected_check_out,
                    sessions_count, is_first_punch, is_complete,
                    total_work_minutes, total_break_minutes, total_overtime_minutes,
                    late_minutes, early_leave_minutes,
                    notes, calculated_at,
                    created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                batch,
            )
        except Exception as e:
            print(f"  ERROR flushing summaries: {e}")

    # ==================================================================
    # Step 14: Employee Groups (att_attgroup + att_attemployee)
    # ==================================================================

    def migrate_employee_groups(self) -> dict[int, int]:
        """Import attendance groups and link employees to them."""
        print("=" * 60)
        print("Step 14: Migrating Employee Groups/Categories")
        print("=" * 60)

        self.db.execute("""
            CREATE TABLE IF NOT EXISTS employee_groups (
                id INT PRIMARY KEY,
                code VARCHAR(50),
                name VARCHAR(200),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            )
        """)
        self.commit()

        group_data = self.parser.get_table_data("att_attgroup")
        ts = now_ts()
        count = 0

        for row in group_data:
            gid = safe_int(row.get("id"))
            code = row.get("code") or ""
            name = row.get("name") or ""

            if gid and not self.dry_run:
                try:
                    self.db.execute(
                        "INSERT IGNORE INTO employee_groups (id, code, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
                        (gid, code, name, ts, ts),
                    )
                    count += 1
                except Exception:
                    pass

        print(f"  Inserted {count} employee groups")

        emp_data = self.parser.get_table_data("att_attemployee")
        updated = 0

        for row in emp_data:
            emp_id = safe_int(row.get("emp_id"))
            group_id = safe_int(row.get("group_id"))

            if emp_id and group_id and not self.dry_run:
                try:
                    self.db.execute(
                        "UPDATE users SET grade_id = ? WHERE id = ?",
                        (group_id, emp_id),
                    )
                    if self.db.db_type == "sqlite":
                        pass  # No rowcount in SQLite for UPDATE
                    updated += 1
                except Exception:
                    pass

        self.commit()
        print(f"  Linked {updated} employees to groups")
        print()
        return {}

    # ==================================================================
    # Helpers
    # ==================================================================

    def _get_ids(self, map_name: str) -> list[int]:
        """Get list of IDs from id_map."""
        return sorted(set(self.id_maps.get(map_name, {}).values()))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Migrate ZKTeco PostgreSQL dump to Laravel HRM database"
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=DEFAULT_DB,
        help=f"Path to SQLite database (default: {DEFAULT_DB})",
    )
    parser.add_argument(
        "--dump",
        type=Path,
        default=DEFAULT_DUMP,
        help=f"Path to PostgreSQL dump file (default: {DEFAULT_DUMP})",
    )
    parser.add_argument(
        "--step",
        type=str,
        default="all",
        choices=[
            "all", "companies", "branches", "departments", "positions",
            "zones", "shifts", "employees", "devices", "attendance",
            "holidays", "vacations", "fingerprints", "daily_summaries",
            "employee_groups",
        ],
        help="Migration step to run (default: all)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse dump without inserting data",
    )
    parser.add_argument(
        "--start-from",
        type=str,
        default=None,
        choices=[
            "companies", "branches", "departments", "positions",
            "zones", "shifts", "employees", "devices", "attendance",
            "holidays", "vacations", "fingerprints", "daily_summaries",
            "employee_groups",
        ],
        help="Start migration from this step (inclusive)",
    )
    parser.add_argument(
        "--mysql",
        action="store_true",
        help="Connect to MySQL database using .env credentials",
    )
    args = parser.parse_args()

    # Validate files
    if not args.dump.exists():
        print(f"ERROR: Dump file not found: {args.dump}")
        sys.exit(1)

    use_mysql = args.mysql

    if not args.dry_run:
        if use_mysql:
            if not HAS_PYMYSQL:
                print("ERROR: pymysql is not installed. Run:")
                print("  pip install pymysql")
                sys.exit(1)
            env_file = DEFAULT_ENV
            if not env_file.exists():
                print(f"ERROR: .env file not found at {env_file}")
                sys.exit(1)
        elif not args.db.exists():
            print(f"ERROR: Database file not found: {args.db}")
            print("Make sure you've run the Laravel migrations first:")
            print("  php artisan migrate")
            sys.exit(1)

    print("=" * 60)
    print("HRM Data Migration Tool")
    print("=" * 60)
    print(f"Dump file:   {args.dump}")
    print(f"Database:    {'MySQL (.env)' if use_mysql else args.db}")
    print(f"Dry run:     {args.dry_run}")
    print(f"Step:        {args.step}")
    if args.start_from:
        print(f"Start from:  {args.start_from}")
    print()

    start_time = time.time()

    # Parse dump
    tables_to_parse: list[str] | None = None
    if args.step != "all":
        # Map step to required tables
        step_tables: dict[str, list[str]] = {
            "companies": ["personnel_company"],
            "branches": [],  # No source table
            "departments": ["personnel_department"],
            "positions": ["personnel_position"],
            "zones": ["personnel_area"],
            "shifts": ["att_timeinterval"],
            "employees": ["personnel_employee"],
            "devices": ["iclock_terminal"],
            "attendance": ["iclock_transaction"],
            "holidays": ["att_holiday"],
            "vacations": ["att_leave", "att_paycode"],
            "fingerprints": ["iclock_biodata"],
            "daily_summaries": ["att_payloadattcode", "att_payloadpaycode"],
            "employee_groups": ["att_attgroup", "att_attemployee"],
        }
        tables_to_parse = step_tables.get(args.step, [])
        if not tables_to_parse:
            print(f"No tables to parse for step '{args.step}'. Parsing all.")
            tables_to_parse = None

    pg_parser = PgDumpParser(args.dump)
    pg_parser.parse(tables=tables_to_parse)

    # Open database
    db = None if args.dry_run else open_db(args.db if not use_mysql else DEFAULT_ENV, use_mysql=use_mysql)

    try:
        migrator = Migrator(pg_parser, db, dry_run=args.dry_run)

        # Define step order
        all_steps = [
            "companies", "branches", "departments", "positions",
            "zones", "shifts", "employees", "devices", "attendance",
            "holidays", "vacations", "fingerprints", "daily_summaries",
            "employee_groups",
        ]

        # Filter steps
        if args.step == "all":
            if args.start_from:
                try:
                    start_idx = all_steps.index(args.start_from)
                    steps = all_steps[start_idx:]
                except ValueError:
                    print(f"Unknown step: {args.start_from}")
                    sys.exit(1)
            else:
                steps = all_steps
        else:
            steps = [args.step]

        # Run migration steps
        for step in steps:
            step_method = getattr(migrator, f"migrate_{step}", None)
            if step_method is None:
                print(f"WARNING: No migration method for step '{step}'")
                continue

            result = step_method()
            migrator.stats[step] = len(result) if result else 0

    finally:
        if db:
            db.commit()
            db.enable_foreign_keys()
            db.close()

    elapsed = time.time() - start_time
    print("=" * 60)
    print("Migration Summary")
    print("=" * 60)
    for step, count in migrator.stats.items():
        print(f"  {step:15s}: {count:>8d} records")
    print(f"\n  Total time: {elapsed:.1f} seconds")
    print()

    if args.dry_run:
        print("DRY RUN COMPLETE - No data was inserted.")
    else:
        print("Migration complete!")
        print()
        print("Next steps:")
        print("  1. Run attendance processing command:")
        print("     php artisan attendance:process-raw-logs")
        print("  2. Generate daily summaries:")
        print("     php artisan attendance:generate-daily-summaries")
        print("  3. Verify data in the admin panel")


if __name__ == "__main__":
    main()
