<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Convert `user_fingerprints.template_data` from `binary` to `longText`.
     *
     * The original BLOB column is too narrow to store the 2 KB+ templates
     * generated by modern ZKTeco firmware; the column is also opaque to
     * dump/restore operations across MySQL/SQLite. The new representation
     * stores the template as a base64 string which is portable and survives
     * dump/restore without data loss.
     *
     * Doctrine DBAL is not available in this project, so the column
     * type switch is performed through a driver-aware raw statement
     * rather than `Schema::table()->change()`.
     */
    public function up(): void
    {
        if (! Schema::hasColumn('user_fingerprints', 'template_data')) {
            return;
        }

        $driver = DB::connection()->getDriverName();

        if ($driver === 'mysql') {
            DB::statement('ALTER TABLE `user_fingerprints` MODIFY COLUMN `template_data` LONGTEXT NULL');
        } elseif ($driver === 'pgsql') {
            DB::statement('ALTER TABLE user_fingerprints ALTER COLUMN template_data TYPE TEXT');
        } elseif ($driver === 'sqlite') {
            // SQLite has no ALTER TYPE. Recreate the column via a temp table.
            DB::statement('PRAGMA foreign_keys = OFF');
            DB::statement(<<<'SQL'
                CREATE TABLE user_fingerprints_tmp (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    device_id INTEGER NULL,
                    finger_id TINYINT NOT NULL DEFAULT 0,
                    template_data LONGTEXT NULL,
                    template_format VARCHAR(30) NOT NULL DEFAULT 'ZKTeco',
                    template_version INTEGER NOT NULL DEFAULT 9,
                    quality TINYINT NOT NULL DEFAULT 0,
                    is_master TINYINT(1) NOT NULL DEFAULT 0,
                    captured_at TIMESTAMP NULL,
                    synced_at TIMESTAMP NULL,
                    created_at TIMESTAMP NULL,
                    updated_at TIMESTAMP NULL,
                    deleted_at TIMESTAMP NULL,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                    FOREIGN KEY (device_id) REFERENCES fingerprint_devices(id) ON DELETE SET NULL
                )
            SQL);
            DB::statement(<<<'SQL'
                INSERT INTO user_fingerprints_tmp
                    (id, user_id, device_id, finger_id, template_data, template_format,
                     template_version, quality, is_master, captured_at, synced_at,
                     created_at, updated_at, deleted_at)
                SELECT id, user_id, device_id, finger_id, CAST(template_data AS TEXT),
                       template_format, template_version, quality, is_master, captured_at,
                       synced_at, created_at, updated_at, deleted_at
                FROM user_fingerprints
            SQL);
            DB::statement('DROP TABLE user_fingerprints');
            DB::statement('ALTER TABLE user_fingerprints_tmp RENAME TO user_fingerprints');
            DB::statement('CREATE INDEX user_fingerprints_user_id_finger_id_index ON user_fingerprints(user_id, finger_id)');
            DB::statement('CREATE INDEX user_fingerprints_device_id_synced_at_index ON user_fingerprints(device_id, synced_at)');
            DB::statement('CREATE INDEX user_fingerprints_is_master_deleted_at_index ON user_fingerprints(is_master, deleted_at)');
            DB::statement('PRAGMA foreign_keys = ON');
        }
    }

    public function down(): void
    {
        if (! Schema::hasColumn('user_fingerprints', 'template_data')) {
            return;
        }

        $driver = DB::connection()->getDriverName();

        if ($driver === 'mysql') {
            DB::statement('ALTER TABLE `user_fingerprints` MODIFY COLUMN `template_data` BLOB NULL');
        } elseif ($driver === 'pgsql') {
            DB::statement('ALTER TABLE user_fingerprints ALTER COLUMN template_data TYPE BYTEA USING NULL');
        }
        // SQLite has no BLOB ↔ TEXT rollback that preserves data, so we leave
        // the column in its upgraded form on the way down.
    }
};
